export default [
  'Alta',
  'American Fork',
  'Beaver',
  'Blanding',
  'Brian Head',
  'Brigham City',
  'Bryce Canyon',
  'Cedar City',
  'Clearfield',
  'Coalville',
  'Delta',
  'Draper',
  'Fillmore',
  'Glendale',
  'Green River',
  'Heber City',
  'Hurricane',
  'Ivins',
  'Kanab',
  'Layton',
  'Lehi',
  'Logan',
  'Midvale',
  'Midway',
  'Milford',
  'Moab',
  'Monticello',
  'Monument Valley',
  'Mount Carmel Junction',
  'Murray',
  'Nephi',
  'Ogden',
  'Orem',
  'Panguitch',
  'Park City',
  'Parowan',
  'Payson',
  'Price',
  'Provo',
  'Richfield',
  'Roosevelt',
  'Saint George',
  'Salina',
  'Salt Lake City',
  'Sandy',
  'Scipio',
  'South Jordan',
  'Springdale',
  'Springville',
  'St George',
  'Tooele',
  'Torrey',
  'Tropic',
  'Vernal',
  'Wendover',
  'West Jordan',
  'West Valley City',
  'Woods Cross'
]